image: Visual Studio 2017 Preview

init:
  - git config --global core.autocrlf input

install:
  - nuget install redis-64 -excludeversion
  - redis-64\tools\redis-server.exe --service-install
  - redis-64\tools\redis-server.exe --service-start

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - docs/*

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -Version "$env:APPVEYOR_REPO_TAG_NAME" -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
- path: .\.nupkgs\*.nupkg
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/miniprofiler/api/v2
  on:
    branch: master  
  api_key:
    secure: LLyiHXh/pU4i8H2Cn74C5sXNV+5MX0gpJZuunTnXv/KoafhfmkB/65/TcV4B7kj2
  symbol_server: https://www.myget.org/F/miniprofiler/symbols/api/v2/package
- provider: NuGet
  server: https://www.myget.org/F/stackoverflow/api/v2
  on:
    branch: master  
  api_key:
    secure: P/UHxq2DEs0GI1SoDXDesHjRVsSVgdywz5vmsnhFQQY5aJgO3kP+QfhwfhXz19Rw
  symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package