image: Visual Studio 2017
version: 4.0.0-alpha{build}

init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: .\build.ps1 -VersionSuffix "alpha$env:appveyor_build_number""

test: off
artifacts:
- path: .\.nupkgs\*.nupkg
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/miniprofiler/api/v2
  on:
    branch: master  
  api_key:
    secure: LLyiHXh/pU4i8H2Cn74C5sXNV+5MX0gpJZuunTnXv/KoafhfmkB/65/TcV4B7kj2
  symbol_server: https://www.myget.org/F/miniprofiler/symbols/api/v2/package